//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSettlersCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheSettlersCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тёмные священики.
        /// </summary>
        public static string QUEST_DARK_PRIESTS {
            get {
                return ResourceManager.GetString("QUEST_DARK_PRIESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Берсерк.
        /// </summary>
        public static string UNIT_BERSERK {
            get {
                return ResourceManager.GetString("UNIT_BERSERK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большая Берта.
        /// </summary>
        public static string UNIT_BIG_BERTHA {
            get {
                return ResourceManager.GetString("UNIT_BIG_BERTHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучник.
        /// </summary>
        public static string UNIT_BOWMAN {
            get {
                return ResourceManager.GetString("UNIT_BOWMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучник дезертир.
        /// </summary>
        public static string UNIT_BOWMAN_DESERTER {
            get {
                return ResourceManager.GetString("UNIT_BOWMAN_DESERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кальтроп.
        /// </summary>
        public static string UNIT_CALTROP {
            get {
                return ResourceManager.GetString("UNIT_CALTROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канонир.
        /// </summary>
        public static string UNIT_CANNONNEER {
            get {
                return ResourceManager.GetString("UNIT_CANNONNEER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канонир дезертир.
        /// </summary>
        public static string UNIT_CANNONNEER_DESERTER {
            get {
                return ResourceManager.GetString("UNIT_CANNONNEER_DESERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тяжёлая конница.
        /// </summary>
        public static string UNIT_CATAPHRACT {
            get {
                return ResourceManager.GetString("UNIT_CATAPHRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кавалерия.
        /// </summary>
        public static string UNIT_CAVALRY {
            get {
                return ResourceManager.GetString("UNIT_CAVALRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кавалерия дезертир.
        /// </summary>
        public static string UNIT_CAVALRY_DESERTER {
            get {
                return ResourceManager.GetString("UNIT_CAVALRY_DESERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чак.
        /// </summary>
        public static string UNIT_CHUCK {
            get {
                return ResourceManager.GetString("UNIT_CHUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стрелок с составным луком.
        /// </summary>
        public static string UNIT_COMPOSITE_BOW {
            get {
                return ResourceManager.GetString("UNIT_COMPOSITE_BOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безумный кок.
        /// </summary>
        public static string UNIT_CRAZY_COOK {
            get {
                return ResourceManager.GetString("UNIT_CRAZY_COOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ворчун.
        /// </summary>
        public static string UNIT_CROAKER {
            get {
                return ResourceManager.GetString("UNIT_CROAKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Арбалетчик.
        /// </summary>
        public static string UNIT_CROSSBOWMAN {
            get {
                return ResourceManager.GetString("UNIT_CROSSBOWMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Арбалетчик дезертир.
        /// </summary>
        public static string UNIT_CROSSBOWMAN_DESERTER {
            get {
                return ResourceManager.GetString("UNIT_CROSSBOWMAN_DESERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сектант.
        /// </summary>
        public static string UNIT_CULTIST {
            get {
                return ResourceManager.GetString("UNIT_CULTIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плящущий дервиш.
        /// </summary>
        public static string UNIT_DANCING_DERVISH {
            get {
                return ResourceManager.GetString("UNIT_DANCING_DERVISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темный первосвященник.
        /// </summary>
        public static string UNIT_DARK_HIGH_PRIEST {
            get {
                return ResourceManager.GetString("UNIT_DARK_HIGH_PRIEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тёмный священник.
        /// </summary>
        public static string UNIT_DARK_PRIEST {
            get {
                return ResourceManager.GetString("UNIT_DARK_PRIEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скребок.
        /// </summary>
        public static string UNIT_DECKSCRUBBER {
            get {
                return ResourceManager.GetString("UNIT_DECKSCRUBBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элитный солдат.
        /// </summary>
        public static string UNIT_ELITE_SOLDIER {
            get {
                return ResourceManager.GetString("UNIT_ELITE_SOLDIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элитный солдат дезертир.
        /// </summary>
        public static string UNIT_ELITE_SOLDIER_DESERTER {
            get {
                return ResourceManager.GetString("UNIT_ELITE_SOLDIER_DESERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фанатик.
        /// </summary>
        public static string UNIT_FANATIC {
            get {
                return ResourceManager.GetString("UNIT_FANATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Танцор огня.
        /// </summary>
        public static string UNIT_FIRE_DANCER {
            get {
                return ResourceManager.GetString("UNIT_FIRE_DANCER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защитник.
        /// </summary>
        public static string UNIT_FULLBACK {
            get {
                return ResourceManager.GetString("UNIT_FULLBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генерал.
        /// </summary>
        public static string UNIT_GENERAL {
            get {
                return ResourceManager.GetString("UNIT_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вратарь.
        /// </summary>
        public static string UNIT_GOALKEEPER {
            get {
                return ResourceManager.GetString("UNIT_GOALKEEPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторожевая собака.
        /// </summary>
        public static string UNIT_GUARD_DOG {
            get {
                return ResourceManager.GetString("UNIT_GUARD_DOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стрелок.
        /// </summary>
        public static string UNIT_GUNMAN {
            get {
                return ResourceManager.GetString("UNIT_GUNMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хускерл.
        /// </summary>
        public static string UNIT_HOUSECARL {
            get {
                return ResourceManager.GetString("UNIT_HOUSECARL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воин ягуар.
        /// </summary>
        public static string UNIT_JAGUAR_WARRIOR {
            get {
                return ResourceManager.GetString("UNIT_JAGUAR_WARRIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Йомсвикинг.
        /// </summary>
        public static string UNIT_JOMVIKING {
            get {
                return ResourceManager.GetString("UNIT_JOMVIKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карл.
        /// </summary>
        public static string UNIT_KARL {
            get {
                return ResourceManager.GetString("UNIT_KARL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метатель ножей.
        /// </summary>
        public static string UNIT_KNIFETHROWER {
            get {
                return ResourceManager.GetString("UNIT_KNIFETHROWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всадник с копьём.
        /// </summary>
        public static string UNIT_LANCE_RIDER {
            get {
                return ResourceManager.GetString("UNIT_LANCE_RIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучник с длинным луком.
        /// </summary>
        public static string UNIT_LONGBOWMAN {
            get {
                return ResourceManager.GetString("UNIT_LONGBOWMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучник с длинным луком дезертир.
        /// </summary>
        public static string UNIT_LONGBOWMAN_DESERTER {
            get {
                return ResourceManager.GetString("UNIT_LONGBOWMAN_DESERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фиксатый.
        /// </summary>
        public static string UNIT_METAL_TOOTHED {
            get {
                return ResourceManager.GetString("UNIT_METAL_TOOTHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полузащитник.
        /// </summary>
        public static string UNIT_MIDFIELDER {
            get {
                return ResourceManager.GetString("UNIT_MIDFIELDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ополченец.
        /// </summary>
        public static string UNIT_MILITIA {
            get {
                return ResourceManager.GetString("UNIT_MILITIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ополченец дезертир.
        /// </summary>
        public static string UNIT_MILITIA_DESERTER {
            get {
                return ResourceManager.GetString("UNIT_MILITIA_DESERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исчадие ада.
        /// </summary>
        public static string UNIT_NIGHT_SPAWN {
            get {
                return ResourceManager.GetString("UNIT_NIGHT_SPAWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кочевник.
        /// </summary>
        public static string UNIT_NOMAD {
            get {
                return ResourceManager.GetString("UNIT_NOMAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одноглазый Берт.
        /// </summary>
        public static string UNIT_ONE_EYED_BERT {
            get {
                return ResourceManager.GetString("UNIT_ONE_EYED_BERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старшина 2-го класса.
        /// </summary>
        public static string UNIT_PETTY_OFFICER_2ND_CLASS {
            get {
                return ResourceManager.GetString("UNIT_PETTY_OFFICER_2ND_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейнджер.
        /// </summary>
        public static string UNIT_RANGER {
            get {
                return ResourceManager.GetString("UNIT_RANGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новобранец.
        /// </summary>
        public static string UNIT_RECRUIT {
            get {
                return ResourceManager.GetString("UNIT_RECRUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новобранец дезертир.
        /// </summary>
        public static string UNIT_RECRUIT_DESERTER {
            get {
                return ResourceManager.GetString("UNIT_RECRUIT_DESERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Амазонки наездницы.
        /// </summary>
        public static string UNIT_RIDING_AMAZONIAN {
            get {
                return ResourceManager.GetString("UNIT_RIDING_AMAZONIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всадник с луком.
        /// </summary>
        public static string UNIT_RIDING_BOWMAN {
            get {
                return ResourceManager.GetString("UNIT_RIDING_BOWMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хулиган.
        /// </summary>
        public static string UNIT_ROUGHNECK {
            get {
                return ResourceManager.GetString("UNIT_ROUGHNECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подстрекатель.
        /// </summary>
        public static string UNIT_SABER_RATTLER {
            get {
                return ResourceManager.GetString("UNIT_SABER_RATTLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старьёвщик.
        /// </summary>
        public static string UNIT_SCAVENGER {
            get {
                return ResourceManager.GetString("UNIT_SCAVENGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крадущийся.
        /// </summary>
        public static string UNIT_SHADOW_SNEAKER {
            get {
                return ResourceManager.GetString("UNIT_SHADOW_SNEAKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаман.
        /// </summary>
        public static string UNIT_SHAMAN {
            get {
                return ResourceManager.GetString("UNIT_SHAMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сэр Робин.
        /// </summary>
        public static string UNIT_SIR_ROBIN {
            get {
                return ResourceManager.GetString("UNIT_SIR_ROBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скунс.
        /// </summary>
        public static string UNIT_SKUNK {
            get {
                return ResourceManager.GetString("UNIT_SKUNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Солдат.
        /// </summary>
        public static string UNIT_SOLDIER {
            get {
                return ResourceManager.GetString("UNIT_SOLDIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Солдат дезертир.
        /// </summary>
        public static string UNIT_SOLDIER_DESERTER {
            get {
                return ResourceManager.GetString("UNIT_SOLDIER_DESERTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пращник.
        /// </summary>
        public static string UNIT_STONE_THROWER {
            get {
                return ResourceManager.GetString("UNIT_STONE_THROWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нападающий.
        /// </summary>
        public static string UNIT_STRIKER {
            get {
                return ResourceManager.GetString("UNIT_STRIKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болотная ведьма.
        /// </summary>
        public static string UNIT_SWAMP_WITCH {
            get {
                return ResourceManager.GetString("UNIT_SWAMP_WITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невольник.
        /// </summary>
        public static string UNIT_THRALL {
            get {
                return ResourceManager.GetString("UNIT_THRALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головорез.
        /// </summary>
        public static string UNIT_THUG {
            get {
                return ResourceManager.GetString("UNIT_THUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Член племени.
        /// </summary>
        public static string UNIT_TRIBESMAN {
            get {
                return ResourceManager.GetString("UNIT_TRIBESMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ревущий бык.
        /// </summary>
        public static string UNIT_UPROARIOUS_BULL {
            get {
                return ResourceManager.GetString("UNIT_UPROARIOUS_BULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валькирия.
        /// </summary>
        public static string UNIT_VALKYRIE {
            get {
                return ResourceManager.GetString("UNIT_VALKYRIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дикия Мери.
        /// </summary>
        public static string UNIT_WILD_MARY {
            get {
                return ResourceManager.GetString("UNIT_WILD_MARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волк.
        /// </summary>
        public static string UNIT_WOLF {
            get {
                return ResourceManager.GetString("UNIT_WOLF", resourceCulture);
            }
        }
    }
}
